"""empty message

Revision ID: 4fc22915ca87
Revises: 03c3c6301b9f
Create Date: 2022-10-21 23:06:54.021671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc22915ca87'
down_revision = '03c3c6301b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'user_id')
    # ### end Alembic commands ###
